#!/bin/sh
#http://www.hyperchain.net
ulimit -c unlimited
appname=hc
dirname=`dirname $0`
tmp=${dirname#?}
if [ "${dirname%$tmp}" != "/" ]; then
	dirname=$PWD/$dirname
fi
LD_LIBRARY_PATH=$dirname:$dirname/lib
export LD_LIBRARY_PATH
$dirname/$appname $*
